name: Test

on:
  push:
  pull_request:
  release: { types: [created] }
  workflow_dispatch:

permissions: {}

env:
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, nightly]
        features: [--no-default-features, --features=default, --all-features]
        exclude: [{ rust: stable, features: --all-features }]

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: "clippy,rustfmt"

      # Get the current date, used as the cache key.
      - id: cache-key
        run: echo "key=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

      # Get cargo-expand from the cache.
      - uses: actions/cache@v6
        id: cache
        with:
          path: ~/.cargo/bin/*
          key: test-${{ runner.os }}-${{ steps.cache-key.outputs.key }}

      # Install cargo-expand on cache miss. Required for macrotest.
      - run: cargo install cargo-expand
        if: steps.cache.outputs.cache-hit != 'true'

      # Run the actual tests.
      - run: cargo fmt --verbose --check --all
      - run: cargo check --verbose --keep-going ${{ matrix.features }}
      - run: cargo clippy --no-deps --verbose --keep-going ${{ matrix.features }}
      - run: cargo doc --verbose --keep-going ${{ matrix.features }}
      - run: cargo test --verbose ${{ matrix.features }}
